version: '2'
services:
  web:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8081
    links:
      - db
    depends_on:
      - db
  db:
    image: andresvidal/rpi3-mongodb3
    command: bash -c "rm -f db/mongod.lock && mongod --auth"
    volumes:
      - ./data/db:/data/db 
      - ./data/configdb:/data/configdb
    ports:
      - 27017:27017
      - 28017:28017